import { expect, test } from './test-fixtures';
import fs from 'node:fs/promises';

test('bot configuration, banner, roles, private tickets and custom GIF work with the real server', async ({page,context},testInfo)=>{
 test.setTimeout(60000);
 page.on('pageerror',error=>console.error('Browser exception:',error.message));
 await context.addInitScript(()=>localStorage.setItem('zdis.locale','en'));
 const login=await context.request.post('/api/auth/login',{data:{identifier:'admin',password:'cNL2*8o$1F;"'}});
 expect(login.ok()).toBeTruthy();const auth=await login.json();
 const headers={'x-csrf-token':auth.csrfToken};
 const name='Bots browser '+testInfo.project.name+' '+Date.now();
 const created=await context.request.post('/api/groups',{headers,data:{name}});expect(created.status()).toBe(201);
 const {group}=await created.json();
 try{
  const roleResponse=await context.request.post(`/api/groups/${group.id}/roles`,{headers,data:{name:'Gaming',permissions:[]}});expect(roleResponse.status()).toBe(201);
  const gif=await fs.readFile(new URL('../../client/public/media-presets/gifs/hello.gif',import.meta.url));
  const upload=await context.request.post('/api/files',{headers,multipart:{file:{name:'browser.gif',mimeType:'image/gif',buffer:gif}}});expect(upload.status()).toBe(201);
  const {attachment}=await upload.json();
  expect((await context.request.post(`/api/groups/${group.id}/expressions`,{headers,data:{name:'browser_gif',type:'gif',attachmentId:attachment.id}})).status()).toBe(201);
  await page.goto('/');
  if(testInfo.project.name==='mobile-chromium'){
   await page.getByRole('button',{name:'Servers',exact:true}).click();
   await page.getByRole('button',{name:new RegExp(name)}).click();
  }else await page.getByTitle(name,{exact:true}).click();
  await page.getByRole('button',{name:/^general$/,exact:true}).click();
  if(testInfo.project.name==='mobile-chromium')await page.getByRole('button',{name:'Back',exact:true}).click();
  await page.locator('.group-sidebar-head').getByRole('button',{name:new RegExp(name)}).click();
  await page.getByRole('button',{name:'Server settings',exact:true}).click();
  const modal=page.getByRole('dialog',{name:new RegExp(name)});
  await modal.getByRole('button',{name:'Server Bots',exact:true}).click();
  await modal.getByRole('checkbox',{name:'Enable Welcomer Bot',exact:true}).check();
  await modal.getByRole('combobox',{name:'Welcome channel',exact:true}).selectOption({label:'#general'});
  await modal.getByRole('textbox',{name:'Welcome message',exact:true}).fill('Welcome {mention} to {server}');
  await modal.getByRole('button',{name:'Auto moderation',exact:true}).click();
  await modal.getByRole('checkbox',{name:'Enable Moderator Bot',exact:true}).check();
  await modal.getByRole('button',{name:'Levels & responses',exact:true}).click();
  await modal.getByRole('group',{name:'Roles members may choose themselves'}).getByRole('checkbox',{name:'Gaming',exact:true}).check();
  await modal.getByRole('button',{name:'Tickets',exact:true}).click();
  await modal.getByRole('checkbox',{name:'Enable private support tickets',exact:true}).check();
  const saved=page.waitForResponse(response=>response.request().method()==='PUT'&&response.url().endsWith(`/api/builtin-bots/groups/${group.id}`));
  await modal.locator('.bot-save').getByRole('button').click();expect((await saved).status()).toBe(200);
  await modal.getByRole('button',{name:'Welcomer',exact:true}).click();
  await modal.getByRole('button',{name:'Preview banner',exact:true}).click();
  await expect(modal.locator('.bot-banner-preview')).toBeVisible();
  await expect.poll(()=>modal.locator('.bot-banner-preview').evaluate((image:HTMLImageElement)=>image.naturalWidth)).toBe(1000);
  await page.evaluate(()=>document.documentElement.dataset.theme='light');
  await page.screenshot({path:testInfo.outputPath('bots-settings.png')});
  await modal.getByRole('button',{name:'Close',exact:true}).click();
  if(testInfo.project.name==='mobile-chromium')await page.getByRole('button',{name:'general',exact:true}).click();
  await page.getByRole('button',{name:'Choose server roles',exact:true}).click();
  const roles=page.getByRole('dialog',{name:'Choose server roles',exact:true});
  await roles.getByRole('button',{name:'Gaming',exact:true}).click();
  await expect(roles.getByRole('button',{name:'✓ Gaming',exact:true})).toHaveAttribute('aria-pressed','true');
  await roles.getByRole('button',{name:'✓ Gaming',exact:true}).click();
  await expect(roles.getByRole('button',{name:'Gaming',exact:true})).toHaveAttribute('aria-pressed','false');
  await roles.getByRole('button',{name:'Close role picker'}).click();
  await page.getByRole('button',{name:'Support tickets',exact:true}).click();
  const tickets=page.getByRole('dialog',{name:'Support tickets',exact:true});
  await tickets.getByRole('textbox',{name:'Ticket topic',exact:true}).fill('Browser private support request');
  await tickets.getByRole('button',{name:'Create private ticket',exact:true}).click();
  await expect(tickets.getByRole('link',{name:'Download transcript'})).toBeVisible();
  await tickets.getByRole('button',{name:'Close support tickets'}).click();
  await page.getByRole('button',{name:'GIF',exact:true}).click();
  const picker=page.getByRole('dialog',{name:'GIF picker'});
  await picker.getByRole('button',{name:'Server',exact:true}).click();
  await picker.getByTitle('browser_gif',{exact:true}).click();
  await expect(page.getByRole('textbox',{name:'Message # general'})).toHaveValue(`<gif:browser_gif:${attachment.id}>`);
  await page.evaluate(()=>{(window as any).__sendEvents=[];for(const type of ['pointerdown','pointerup','click'])document.addEventListener(type,event=>{const target=event.target as HTMLElement;(window as any).__sendEvents.push({type,tag:target.tagName,title:target.closest('button')?.title});},true);});
  const delivered=page.waitForResponse(response=>response.request().method()==='POST'&&response.url().includes('/messages'),{timeout:10000});
  if(testInfo.project.name==='mobile-chromium')await page.getByRole('button',{name:'Send (Enter)',exact:true}).tap();
  else await page.getByRole('button',{name:'Send (Enter)',exact:true}).click();
  const sendResponse=await delivered.catch(async error=>{console.error('Send events:',await page.evaluate(()=>(window as any).__sendEvents));await page.screenshot({path:testInfo.outputPath('send-before-cleanup.png')});throw error;});
  expect(sendResponse.status()).toBe(201);
  await expect(page.locator(`.custom-sticker[src="/api/files/${attachment.id}"]`)).toBeVisible();
  await expect.poll(()=>page.locator(`.custom-sticker[src="/api/files/${attachment.id}"]`).evaluate((image:HTMLImageElement)=>image.naturalWidth)).toBeGreaterThan(0);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 }finally{await context.request.delete(`/api/groups/${group.id}`,{headers}).catch(error=>console.warn('Browser fixture cleanup deferred to isolated database cleanup:',error.message));}
});
