import {useEffect,useState} from 'react';
import {api} from '../lib/api';
import type {AdminUser,Badge} from '../types';
const features=[['sendFiles','ارسال فایل'],['sendImages','ارسال عکس'],['sendVideos','ارسال فیلم'],['sendAudio','ارسال صوت'],['connectVoice','ورود به ویس'],['speak','صحبت کردن'],['video','دوربین'],['screenShare','اشتراک صفحه']] as const;
const limits=[['maxOwnedGroups','سقف گروه‌های ساخته‌شده','default_max_owned_groups'],['maxJoinedGroups','سقف عضویت گروه‌ها','default_max_joined_groups'],['maxCreatedChannels','سقف کانال‌های ساخته‌شده','default_max_created_channels'],['maxChannelsPerGroup','سقف کانال هر گروه','default_max_channels_per_group']] as const;
type Policy=Record<string,boolean|number>;
export function AdminAccess(){
 const [users,setUsers]=useState<AdminUser[]>([]),[selected,setSelected]=useState(''),[defaults,setDefaults]=useState<Policy>({}),[overrides,setOverrides]=useState<Policy>({}),[badges,setBadges]=useState<Badge[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[label,setLabel]=useState(''),[color,setColor]=useState('#5865f2'),[icon,setIcon]=useState('star');
 async function load(){const [s,u,b]=await Promise.all([api.get<{settings:Policy}>('/api/admin/settings'),api.get<{users:AdminUser[]}>('/api/admin/users?limit=500'),api.get<{badges:Badge[]}>('/api/admin/badges')]);setDefaults(s.settings);setUsers(u.users);setBadges(b.badges);}
 async function run(action:()=>Promise<void>){setBusy(true);setError('');try{await action();}catch(e){setError(e instanceof Error?e.message:'خطا');}finally{setBusy(false);}}
 useEffect(()=>{void run(load);},[]);
 useEffect(()=>{if(selected)void run(async()=>{const data=await api.get<{overrides:Policy}>(`/api/admin/users/${selected}/access`);setOverrides(data.overrides);});else setOverrides({});},[selected]);
 const reset=(key:string)=>setOverrides(current=>{const next={...current};delete next[key];return next;});
 return <section className="settings-group admin-card"><h3>دسترسی افراد، سقف‌ها و بج‌های اختصاصی</h3>{error?<p role="alert">{error}</p>:null}<fieldset disabled={busy}><legend>پیش‌فرض همهٔ حساب‌ها</legend><div className="grid-2">{limits.map(([key,title,setting])=><label className="field" key={key}><span>{title}</span><input className="input" type="number" min={key==='maxChannelsPerGroup'?3:0} max={10000} value={Number(defaults[setting]??0)} onChange={e=>setDefaults({...defaults,[setting]:Number(e.target.value)})}/></label>)}</div>{features.map(([key,title])=><label className="checkbox" key={key}><input type="checkbox" checked={Boolean(defaults['default_'+key])} onChange={e=>setDefaults({...defaults,['default_'+key]:e.target.checked})}/><span>{title}</span></label>)}<button className="btn primary" onClick={()=>void run(async()=>{const patch:Policy={};for(const [, ,setting]of limits)patch[setting]=defaults[setting];for(const [key]of features)patch['default_'+key]=defaults['default_'+key];await api.patch('/api/admin/settings',patch);})}>ذخیره پیش‌فرض‌ها</button></fieldset>
 <fieldset disabled={busy}><legend>استثنا برای هر فرد</legend><label className="field"><span>حساب</span><select className="select" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">انتخاب حساب</option>{users.map(u=><option key={u.id} value={u.id}>{u.displayName} (@{u.username})</option>)}</select></label>{selected?<><p className="hint">«پیش‌فرض» از تنظیمات عمومی پیروی می‌کند. صفر یعنی اجازهٔ ایجاد یا عضویت جدید ندارد؛ موارد قبلی حذف نمی‌شوند.</p><div className="grid-2">{limits.map(([key,title,setting])=><label className="field" key={key}><span>{title} (پیش‌فرض: {Number(defaults[setting])})</span><input className="input" type="number" min={0} max={10000} placeholder="پیش‌فرض" value={overrides[key]===undefined?'':Number(overrides[key])} onChange={e=>e.target.value===''?reset(key):setOverrides({...overrides,[key]:Number(e.target.value)})}/></label>)}</div>{features.map(([key,title])=><label className="field" key={key}><span>{title}</span><select className="select" value={overrides[key]===undefined?'inherit':String(overrides[key])} onChange={e=>e.target.value==='inherit'?reset(key):setOverrides({...overrides,[key]:e.target.value==='true'})}><option value="inherit">پیش‌فرض ({defaults['default_'+key]?'فعال':'غیرفعال'})</option><option value="true">فعال</option><option value="false">غیرفعال</option></select></label>)}<button className="btn primary" onClick={()=>void run(async()=>{await api.put(`/api/admin/users/${selected}/access`,overrides);})}>ذخیره دسترسی فرد</button><button className="btn ghost" onClick={()=>void run(async()=>{await api.put(`/api/admin/users/${selected}/access`,{});setOverrides({});})}>بازگشت به پیش‌فرض</button></>:null}</fieldset>
 <fieldset disabled={busy}><legend>بج اختصاصی</legend><p className="hint">بج اختصاصی نمایشی است؛ برای اعطای دسترسی از نقش و تنظیمات بالا استفاده کنید. اعطا و حذف بج هر فرد در ویرایش حساب است.</p><label className="field"><span>عنوان بج</span><input className="input" value={label} maxLength={60} onChange={e=>setLabel(e.target.value)}/></label><label className="field"><span>رنگ</span><input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><label className="field"><span>نماد</span><select className="select" value={icon} onChange={e=>setIcon(e.target.value)}>{['star','shield','code','camera','broadcast','handshake','palette','scissors','check'].map(i=><option key={i}>{i}</option>)}</select></label><button className="btn" disabled={!label.trim()} onClick={()=>void run(async()=>{await api.post('/api/admin/badges',{label,color,icon});setLabel('');await load();})}>افزودن بج</button>{badges.filter(b=>b.id.startsWith('custom_')).map(b=><div className="row between" key={b.id}><span style={{color:b.color??undefined}}>{b.label}</span><button className="btn danger small" onClick={()=>void run(async()=>{await api.del(`/api/admin/badges/${b.id}`);await load();})}>حذف بج از همهٔ افراد</button></div>)}</fieldset></section>;
}
