import {listBotSelfRoles,selectBotSelfRole} from '../services/botSelfRoles.js';
import { listBotTickets, createBotTicket, updateBotTicket, botTicketTranscript } from '../services/botTickets.js';
import express from 'express';
import { asyncRoute, badRequest, forbidden, notFound } from '../lib/errors.js';
import { parse, z, idSchema } from '../lib/validate.js';
import { requireAuth } from '../middleware/auth.js';
import { writeLimiter } from '../middleware/rateLimit.js';
import { requireGroupPermission, groupContext } from '../services/permissions.js';
import { getDb } from '../db/index.js';
import { botSettings, saveBotSettings, sendWelcome, renderWelcomeBanner, botTemplateValues, moderatorAction, BOT_VARIABLES, ensureBuiltinBots } from '../services/builtinBots.js';
import { BOT_DEFAULTS, levelForXp } from '../services/botRules.js';

const nullableId=idSchema.nullable().default(null), ids=z.array(idSchema).max(30).default([]), color=z.string().regex(/^#[0-9a-fA-F]{6}$/);
export const botSettingsSchema=z.object({
 welcomer:z.object({enabled:z.boolean(),welcomeChannelId:nullableId,goodbyeChannelId:nullableId,welcomeMessage:z.string().max(3000),goodbyeMessage:z.string().max(3000),bannerEnabled:z.boolean(),bannerTitle:z.string().max(180),bannerSubtitle:z.string().max(240),goodbyeTitle:z.string().max(180),bannerColor:color,textColor:color,backgroundAttachmentId:nullableId,autoRoleIds:ids}),
 moderator:z.object({protectionEnabled:z.boolean().default(false),protectionWhitelistIds:ids,protectedUserIds:ids,protectedRoleIds:ids,maxActionsPerWindow:z.number().int().min(1).max(100).default(5),protectionWindowSeconds:z.number().int().min(5).max(3600).default(60),logsEnabled:z.boolean().default(false),temporaryVoiceEnabled:z.boolean().default(false),temporaryVoiceCategoryId:nullableId,temporaryVoiceIdleSeconds:z.number().int().min(60).max(3600).default(300),temporaryInvitesEnabled:z.boolean().default(false),starboardEnabled:z.boolean().default(false),starboardChannelId:nullableId,starboardThreshold:z.number().int().min(1).max(100).default(3),starboardEmoji:z.string().min(1).max(32).default("\u2b50"),antiRaidEnabled:z.boolean().default(false),maxJoinsPerWindow:z.number().int().min(1).max(1000).default(10),joinWindowSeconds:z.number().int().min(5).max(3600).default(60),minAccountAgeHours:z.number().int().min(0).max(8760).default(0),enabled:z.boolean(),logChannelId:nullableId,blockedWords:z.array(z.string().trim().min(1).max(100)).max(100),blockLinks:z.boolean(),blockInvites:z.boolean(),allowedDomains:z.array(z.string().trim().toLowerCase().regex(/^(?:[a-z0-9-]+\.)+[a-z]{2,}$/)).max(50),maxMentions:z.number().int().min(0).max(100),maxMessages:z.number().int().min(2).max(100),windowSeconds:z.number().int().min(2).max(120),maxRepeats:z.number().int().min(1).max(50),capsPercent:z.number().int().min(10).max(100),minCapsLength:z.number().int().min(5).max(1000),maxAttachments:z.number().int().min(0).max(10),action:z.enum(['block','timeout']),timeoutSeconds:z.number().int().min(60).max(28*86400),warningThreshold:z.number().int().min(1).max(100),exemptRoleIds:ids,exemptChannelIds:ids,levelingEnabled:z.boolean(),voiceXpPerMinute:z.number().int().min(0).max(100).default(15),xpPerMessage:z.number().int().min(1).max(100),xpCooldownSeconds:z.number().int().min(10).max(86400),selfRoleIds:ids,levelRewards:z.array(z.object({type:z.enum(['text','voice']).default('text'),level:z.number().int().min(1).max(1000),roleId:idSchema})).max(20),responses:z.array(z.object({trigger:z.string().trim().min(1).max(120),response:z.string().min(1).max(2000),exact:z.boolean()})).max(30),ticketsEnabled:z.boolean(),ticketCategoryId:nullableId,ticketSupportRoleIds:ids})
});
export const botActionSchema=z.object({action:z.enum(['move','bulkRole','setColor','setXp','setLevel','resetXp','voiceKick','muteText','unmuteText','muteVoice','unmuteVoice','pointsSet','pointsIncrease','pointsDecrease','pointsReset','removeWarning','warn','clearWarnings','timeout','untimeout','kick','ban','unban','purge','lock','unlock','slowmode','nickname','role']),userIds:z.array(idSchema).max(100).optional(),color:color.optional(),xp:z.number().int().min(0).max(1000000000).optional(),level:z.number().int().min(0).max(1000).optional(),xpType:z.enum(['text','voice']).default('text'),botsOnly:z.boolean().default(false),points:z.number().int().min(0).max(1000000).optional(),warningId:z.string().uuid().optional(),userId:idSchema.optional(),channelId:idSchema.optional(),reason:z.string().trim().max(500).default('No reason supplied'),durationSeconds:z.number().int().min(0).max(28*86400).default(600),count:z.number().int().min(1).max(100).default(20),nickname:z.string().trim().max(32).optional(),roleId:idSchema.optional(),remove:z.boolean().default(false),temporary:z.boolean().default(false)});
export const builtinBotsRouter=express.Router();builtinBotsRouter.use(requireAuth);
builtinBotsRouter.get('/groups/:groupId',asyncRoute(async(req,res)=>{const id=parse(idSchema,req.params.groupId),ctx=await groupContext(id,req.user);if(!ctx.can('manageGroup')&&!ctx.can('moderateMembers'))throw forbidden('Server management or moderation permission is required.');res.json({...await botSettings(id),defaults:BOT_DEFAULTS,variables:BOT_VARIABLES});}));
builtinBotsRouter.put('/groups/:groupId',writeLimiter,asyncRoute(async(req,res)=>{const id=parse(idSchema,req.params.groupId),body=parse(z.object({settings:botSettingsSchema,revision:z.number().int().min(0)}),req.body);res.json(await saveBotSettings(id,req.user,body.settings,body.revision));}));
builtinBotsRouter.get('/groups/:groupId/status',asyncRoute(async(req,res)=>{const id=parse(idSchema,req.params.groupId);await groupContext(id,req.user);const {settings}=await botSettings(id);res.json({welcomer:settings.welcomer.enabled,moderator:settings.moderator.enabled,tickets:settings.moderator.enabled&&settings.moderator.ticketsEnabled});}));
builtinBotsRouter.post('/groups/:groupId/preview',writeLimiter,asyncRoute(async(req,res)=>{const id=parse(idSchema,req.params.groupId);await requireGroupPermission(id,req.user,'manageGroup');const body=parse(z.object({settings:botSettingsSchema,kind:z.enum(['join','leave']).default('join')}),req.body), values=await botTemplateValues(id,req.user.id);const bg=body.settings.welcomer.backgroundAttachmentId;if(bg){const {settings}=await botSettings(id);if(settings.welcomer.backgroundAttachmentId!==bg&&!await getDb().get('SELECT id FROM attachments WHERE id=? AND uploader_id=?',[bg,req.user.id]))throw forbidden('Background image access denied.');}res.type('png').set('Cache-Control','no-store').send(await renderWelcomeBanner(body.settings.welcomer,values,body.kind));}));
builtinBotsRouter.post('/groups/:groupId/test',writeLimiter,asyncRoute(async(req,res)=>{const id=parse(idSchema,req.params.groupId);await requireGroupPermission(id,req.user,'manageGroup');const body=parse(z.object({kind:z.enum(['join','leave'])}),req.body);const message=await sendWelcome(id,req.user.id,body.kind);if(!message)throw badRequest('Enable Welcomer and select this event channel first.');res.json({message});}));
builtinBotsRouter.post('/groups/:groupId/actions',writeLimiter,asyncRoute(async(req,res)=>res.json(await moderatorAction(parse(idSchema,req.params.groupId),req.user,parse(botActionSchema,req.body)))));
builtinBotsRouter.get('/groups/:groupId/cases',asyncRoute(async(req,res)=>{const id=parse(idSchema,req.params.groupId);await requireGroupPermission(id,req.user,'moderateMembers');res.json({cases:await getDb().all('SELECT c.*,u.username,u.display_name FROM builtin_bot_cases c LEFT JOIN users u ON u.id=c.user_id WHERE group_id=? ORDER BY created_at DESC LIMIT 100',[id])});}));
builtinBotsRouter.get('/groups/:groupId/leaderboard',asyncRoute(async(req,res)=>{const id=parse(idSchema,req.params.groupId);await groupContext(id,req.user);const rows=await getDb().all('SELECT l.*,u.username,u.display_name FROM builtin_bot_levels l JOIN users u ON u.id=l.user_id JOIN group_members m ON m.group_id=l.group_id AND m.user_id=l.user_id WHERE l.group_id=? ORDER BY xp DESC LIMIT 100',[id]);res.json({members:rows.map(row=>({...row,level:levelForXp(row.xp)}))});}));
builtinBotsRouter.get('/groups/:groupId/tickets',asyncRoute(async(req,res)=>res.json({tickets:await listBotTickets(parse(idSchema,req.params.groupId),req.user)})));
builtinBotsRouter.post('/groups/:groupId/tickets',writeLimiter,asyncRoute(async(req,res)=>{const body=parse(z.object({topic:z.string().trim().min(3).max(500)}),req.body);res.status(201).json({ticket:await createBotTicket(parse(idSchema,req.params.groupId),req.user,body.topic)});}));
builtinBotsRouter.patch('/groups/:groupId/tickets/:ticketId',writeLimiter,asyncRoute(async(req,res)=>{const body=parse(z.object({action:z.enum(['claim','close','reopen'])}),req.body);res.json({ticket:await updateBotTicket(parse(idSchema,req.params.groupId),req.user,parse(idSchema,req.params.ticketId),body.action)});}));
builtinBotsRouter.get('/groups/:groupId/tickets/:ticketId/transcript',asyncRoute(async(req,res)=>{const id=parse(idSchema,req.params.ticketId);res.type('text/plain').set('Content-Disposition',`attachment; filename="ticket-${id}.txt"`).send(await botTicketTranscript(parse(idSchema,req.params.groupId),req.user,id));}));
builtinBotsRouter.get('/groups/:groupId/self-roles',asyncRoute(async(req,res)=>res.json({roles:await listBotSelfRoles(parse(idSchema,req.params.groupId),req.user)})));
builtinBotsRouter.post('/groups/:groupId/self-roles',writeLimiter,asyncRoute(async(req,res)=>{const body=parse(z.object({roleId:idSchema,remove:z.boolean().default(false)}),req.body);res.json({roles:await selectBotSelfRole(parse(idSchema,req.params.groupId),req.user,body.roleId,body.remove)});}));

builtinBotsRouter.get('/groups/:groupId/points',asyncRoute(async(req,res)=>{const groupId=parse(idSchema,req.params.groupId);await requireGroupPermission(groupId,req.user,'moderateMembers');res.json({members:await getDb().all('SELECT p.user_id,p.points,u.username,u.display_name FROM builtin_bot_points p JOIN users u ON u.id=p.user_id WHERE p.group_id=? ORDER BY p.points DESC LIMIT 100',[groupId])});}));

builtinBotsRouter.get('/groups/:groupId/profile/:userId',asyncRoute(async(req,res)=>{const groupId=parse(idSchema,req.params.groupId);await groupContext(groupId,req.user);const {botProfile}=await import('../services/botProfiles.js');res.json({profile:await botProfile(groupId,parse(idSchema,req.params.userId))});}));
builtinBotsRouter.post('/groups/:groupId/profile',writeLimiter,asyncRoute(async(req,res)=>{const groupId=parse(idSchema,req.params.groupId);const body=parse(z.object({action:z.enum(['daily','transfer','rep','title']),userId:idSchema.optional(),amount:z.number().int().min(1).max(1000000).optional(),title:z.string().trim().max(100).optional()}),req.body);const {profileAction}=await import('../services/botProfiles.js');res.json({profile:await profileAction(groupId,req.user,body)});}));

builtinBotsRouter.post('/groups/:groupId/embeds',writeLimiter,asyncRoute(async(req,res)=>{const groupId=parse(idSchema,req.params.groupId);const body=parse(z.object({channelId:idSchema,embed:z.object({title:z.string().trim().max(256).default(''),description:z.string().max(3000).default(''),color:color.default('#5865f2'),footer:z.string().max(500).default(''),fields:z.array(z.object({name:z.string().min(1).max(256),value:z.string().min(1).max(1024),inline:z.boolean().default(false)})).max(25).default([])})}),req.body);const {sendBotEmbed}=await import('../services/botEmbeds.js');res.status(201).json({message:await sendBotEmbed(groupId,req.user,body.channelId,body.embed)});}));

builtinBotsRouter.post('/groups/:groupId/temporary-voice',writeLimiter,asyncRoute(async(req,res)=>{const groupId=parse(idSchema,req.params.groupId),body=parse(z.object({name:z.string().trim().min(1).max(64)}),req.body);const {createTemporaryVoice}=await import('../services/botTemporary.js');res.status(201).json({channel:await createTemporaryVoice(groupId,req.user,body.name)});}));
builtinBotsRouter.post('/groups/:groupId/temporary-invite',writeLimiter,asyncRoute(async(req,res)=>{const groupId=parse(idSchema,req.params.groupId),body=parse(z.object({maxUses:z.number().int().min(1).max(100).default(1),expiresInHours:z.number().min(0.25).max(168).default(1)}),req.body);const {temporaryInvite}=await import('../services/botTemporary.js');res.status(201).json({invite:await temporaryInvite(groupId,req.user,body.maxUses,body.expiresInHours)});}));
