import { useEffect, useRef, useState } from 'react';
import { api } from '../lib/api';
import { useI18n } from '../lib/i18n';
import { Icon } from './Icon';
import { toast } from '../store/toast';
import type { Channel, GroupMember, ServerRole, ChannelCategory } from '../types';

interface Welcomer {enabled:boolean;welcomeChannelId:string|null;goodbyeChannelId:string|null;welcomeMessage:string;goodbyeMessage:string;bannerEnabled:boolean;bannerTitle:string;bannerSubtitle:string;goodbyeTitle:string;bannerColor:string;textColor:string;backgroundAttachmentId:string|null;autoRoleIds:string[]}
interface Moderator {protectionEnabled:boolean;protectionWhitelistIds:string[];protectedUserIds:string[];protectedRoleIds:string[];maxActionsPerWindow:number;protectionWindowSeconds:number;logsEnabled:boolean;temporaryVoiceEnabled:boolean;temporaryVoiceCategoryId:string|null;temporaryVoiceIdleSeconds:number;temporaryInvitesEnabled:boolean;starboardEnabled:boolean;starboardChannelId:string|null;starboardThreshold:number;starboardEmoji:string;antiRaidEnabled:boolean;maxJoinsPerWindow:number;joinWindowSeconds:number;minAccountAgeHours:number;enabled:boolean;logChannelId:string|null;blockedWords:string[];blockLinks:boolean;blockInvites:boolean;allowedDomains:string[];maxMentions:number;maxMessages:number;windowSeconds:number;maxRepeats:number;capsPercent:number;minCapsLength:number;maxAttachments:number;action:'block'|'timeout';timeoutSeconds:number;warningThreshold:number;exemptRoleIds:string[];exemptChannelIds:string[];levelingEnabled:boolean;voiceXpPerMinute:number;xpPerMessage:number;xpCooldownSeconds:number;levelRewards:{type?:'text'|'voice';level:number;roleId:string}[];selfRoleIds:string[];responses:{trigger:string;response:string;exact:boolean}[];ticketsEnabled:boolean;ticketCategoryId:string|null;ticketSupportRoleIds:string[]}
interface Settings {welcomer:Welcomer;moderator:Moderator}
interface BotCase {id:string;action:string;reason:string;username:string|null;created_at:number;active:number}
interface Ticket {id:string;channel_id:string;user_id:string;status:string;claimed_by:string|null}
export function BotsSettings({groupId,channels,members,roles,categories,canManage}:{groupId:string;channels:Channel[];members:GroupMember[];roles:ServerRole[];categories:ChannelCategory[];canManage:boolean}) {
 const {locale}=useI18n(),fa=locale==='fa',t=(en:string,persian:string)=>fa?persian:en;
 const [settings,setSettings]=useState<Settings|null>(null),[revision,setRevision]=useState(0),[variables,setVariables]=useState<string[]>([]),[tab,setTab]=useState('welcome'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[dirty,setDirty]=useState(false),[preview,setPreview]=useState(''),[cases,setCases]=useState<BotCase[]>([]),[tickets,setTickets]=useState<Ticket[]>([]),[action,setAction]=useState('warn'),[userId,setUserId]=useState(''),[channelId,setChannelId]=useState(''),[reason,setReason]=useState(''),[duration,setDuration]=useState(600),[count,setCount]=useState(20),[nickname,setNickname]=useState(''),[roleId,setRoleId]=useState(''),[temporary,setTemporary]=useState(false),[removeRole,setRemoveRole]=useState(false),[bulkUsers,setBulkUsers]=useState(''),[actionColor,setActionColor]=useState('#5865f2'),[points,setPoints]=useState(0),[warningId,setWarningId]=useState(''),[embedTitle,setEmbedTitle]=useState(''),[embedDescription,setEmbedDescription]=useState(''),[embedColor,setEmbedColor]=useState('#5865f2'),[embedFooter,setEmbedFooter]=useState(''),[embedFields,setEmbedFields]=useState<{name:string;value:string;inline:boolean}[]>([]);
 const previewRef=useRef('');
 const path=`/api/builtin-bots/groups/${groupId}`;
 useEffect(()=>{let alive=true;api.get<{settings:Settings;revision:number;variables:string[]}>(path).then(data=>{if(alive){setSettings(data.settings);setRevision(data.revision);setVariables(data.variables);}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;URL.revokeObjectURL(previewRef.current);};},[path]);
 function welcome(patch:Partial<Welcomer>){setSettings(s=>s?{...s,welcomer:{...s.welcomer,...patch}}:s);setDirty(true);}
 function moderate(patch:Partial<Moderator>){setSettings(s=>s?{...s,moderator:{...s.moderator,...patch}}:s);setDirty(true);}
 async function run(task:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await task();}catch(e){setError(e instanceof Error?e.message:'Request failed');}finally{setBusy(false);}}
 async function save(){await run(async()=>{const data=await api.put<{settings:Settings;revision:number}>(path,{settings,revision});setSettings(data.settings);setRevision(data.revision);setDirty(false);toast.success(t('Bot settings saved','تنظیمات ربات ذخیره شد'));});}
 async function refreshCases(){const data=await api.get<{cases:BotCase[]}>(path+'/cases');setCases(data.cases);}
 async function refreshTickets(){const data=await api.get<{tickets:Ticket[]}>(path+'/tickets');setTickets(data.tickets);}
 const channelSelect=(label:string,value:string|null,change:(value:string|null)=>void,types:string[]=['text','announcement'])=><label className="field"><span>{label}</span><select className="select" value={value||''} onChange={e=>change(e.target.value||null)}><option value="">{t('Disabled / select channel','غیرفعال / انتخاب کانال')}</option>{channels.filter(c=>types.includes(c.type)).map(c=><option key={c.id} value={c.id}>#{c.name}</option>)}</select></label>;
 const check=(label:string,checked:boolean,change:(value:boolean)=>void)=><label className="bot-toggle"><input type="checkbox" checked={checked} onChange={e=>change(e.target.checked)}/><span>{label}</span></label>;
 const multiRoles=(label:string,selected:string[],change:(value:string[])=>void)=><fieldset className="bot-role-options"><legend>{label}</legend>{roles.filter(r=>!r.isDefault).map(r=><label key={r.id}><input type="checkbox" checked={selected.includes(r.id)} onChange={e=>change(e.target.checked?[...selected,r.id]:selected.filter(id=>id!==r.id))}/>{r.name}</label>)}</fieldset>;
 const num=(label:string,key:keyof Moderator,min:number,max:number)=><label className="field"><span>{label}</span><input className="input" type="number" min={min} max={max} value={Number(settings?.moderator[key]||0)} onChange={e=>moderate({[key]:Number(e.target.value)})}/></label>;
 if(!settings)return <div className="bot-settings"><p>{error||t('Loading bot settings…','در حال دریافت تنظیمات ربات…')}</p></div>;
 const w=settings.welcomer,m=settings.moderator;
 return <section className="bot-settings">
  <div className="bot-dashboard-head"><div className="bot-logo"><Icon name="code" size={28}/></div><div><h3>{t('Server bots','ربات‌های سرور')}</h3><p>{t('Welcome members. Protect conversations. Build your community.','به اعضا خوشامد بگو، گفتگوها را مدیریت کن و اجتماع خودت را بساز.')}</p></div><span className="bot-verified">✓ BOT</span></div>
  <div className="bot-tabs">{[['welcome','Welcomer','خوشامدگو'],['moderator','Auto moderation','مدیریت خودکار'],['actions','Actions & cases','عملیات و پرونده‌ها'],['community','Levels & responses','سطح‌ها و پاسخ‌ها'],['embeds','Embed builder','پیام قالب‌بندی‌شده'],['tickets','Tickets','تیکت‌ها']].map(([id,en,p])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);if(id==='actions')void run(refreshCases);if(id==='tickets')void run(refreshTickets);}}>{t(en,p)}</button>)}</div>
  {error?<p className="bot-error" role="alert">{error}</p>:null}
  <fieldset disabled={busy||!canManage} className="bot-config-fields">
  {tab==='welcome'?<>
   {check(t('Enable Welcomer Bot','فعال‌کردن ربات خوشامدگو'),w.enabled,v=>welcome({enabled:v}))}
   <div className="bot-form-grid">{channelSelect(t('Welcome channel','کانال خوشامدگویی'),w.welcomeChannelId,v=>welcome({welcomeChannelId:v}))}{channelSelect(t('Goodbye channel','کانال خداحافظی'),w.goodbyeChannelId,v=>welcome({goodbyeChannelId:v}))}</div>
   <label className="field"><span>{t('Welcome message','پیام خوشامدگویی')}</span><textarea className="input" rows={4} maxLength={3000} value={w.welcomeMessage} onChange={e=>welcome({welcomeMessage:e.target.value})}/></label>
   <div className="bot-variables">{variables.map(v=><button key={v} title={t('Insert in welcome message','افزودن به پیام خوشامد')} onClick={()=>welcome({welcomeMessage:w.welcomeMessage+' {'+v+'}'})}>{'{'+v+'}'}</button>)}</div>
   <label className="field"><span>{t('Goodbye message','پیام خداحافظی')}</span><textarea className="input" rows={3} maxLength={3000} value={w.goodbyeMessage} onChange={e=>welcome({goodbyeMessage:e.target.value})}/></label>
   {check(t('Personalized image banner','بنر تصویری شخصی‌سازی‌شده'),w.bannerEnabled,v=>welcome({bannerEnabled:v}))}
   <div className="bot-form-grid"><label className="field"><span>{t('Welcome title','عنوان خوشامد')}</span><input className="input" value={w.bannerTitle} maxLength={180} onChange={e=>welcome({bannerTitle:e.target.value})}/></label><label className="field"><span>{t('Goodbye title','عنوان خداحافظی')}</span><input className="input" value={w.goodbyeTitle} maxLength={180} onChange={e=>welcome({goodbyeTitle:e.target.value})}/></label></div>
   <label className="field"><span>{t('Banner subtitle','زیرعنوان بنر')}</span><input className="input" value={w.bannerSubtitle} maxLength={240} onChange={e=>welcome({bannerSubtitle:e.target.value})}/></label>
   <div className="bot-form-grid"><label className="field"><span>{t('Background color','رنگ زمینه')}</span><input type="color" value={w.bannerColor} onChange={e=>welcome({bannerColor:e.target.value})}/></label><label className="field"><span>{t('Text color','رنگ متن')}</span><input type="color" value={w.textColor} onChange={e=>welcome({textColor:e.target.value})}/></label></div>
   <label className="field"><span>{t('Custom background image (max 8 MB)','تصویر زمینهٔ اختصاصی (حداکثر ۸ مگابایت)')}</span><input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>{const f=e.target.files?.[0];if(f)void run(async()=>{const form=new FormData();form.append('file',f);const r=await api.post<{attachment:{id:string}}>('/api/files',form);welcome({backgroundAttachmentId:r.attachment.id});});}}/></label>{w.backgroundAttachmentId?<button className="btn small" onClick={()=>welcome({backgroundAttachmentId:null})}>{t('Remove background','حذف زمینه')}</button>:null}
   {multiRoles(t('Automatic roles for new members','نقش خودکار اعضای تازه'),w.autoRoleIds,v=>welcome({autoRoleIds:v}))}
   <div className="bot-action-row"><button className="btn" onClick={()=>void run(async()=>{const blob=await api.postBlob(path+'/preview',{settings,kind:'join'});URL.revokeObjectURL(previewRef.current);previewRef.current=URL.createObjectURL(blob);setPreview(previewRef.current);})}>{t('Preview banner','پیش‌نمایش بنر')}</button>{(['join','leave'] as const).map(kind=><button key={kind} className="btn" disabled={dirty} onClick={()=>void run(async()=>{await api.post(path+'/test',{kind});toast.success(t('Test message sent','پیام آزمایشی ارسال شد'));})}>{kind==='join'?t('Send welcome test','تست خوشامد'):t('Send goodbye test','تست خداحافظی')}</button>)}</div>{preview?<img className="bot-banner-preview" src={preview} alt={t('Personalized welcome banner preview','پیش‌نمایش بنر شخصی‌سازی‌شده')}/>:null}
  </>:null}
  {tab==='moderator'?<>
   {check(t('Enable Moderator Bot','فعال‌کردن ربات مدیریت'),m.enabled,v=>moderate({enabled:v}))}
   {channelSelect(t('Moderation log channel','کانال گزارش مدیریت'),m.logChannelId,v=>moderate({logChannelId:v}))}
   {check(t('Anti-raid protection','محافظت در برابر هجوم'),m.antiRaidEnabled,v=>moderate({antiRaidEnabled:v}))}
   <div className="bot-form-grid">{num(t('Maximum joins per window','حداکثر ورود در بازه'),'maxJoinsPerWindow',1,1000)}{num(t('Join window seconds','بازه ورود به ثانیه'),'joinWindowSeconds',5,3600)}{num(t('Minimum account age hours','حداقل عمر حساب به ساعت'),'minAccountAgeHours',0,8760)}</div>
   <label className="field"><span>{t('Blocked words (one per line)','کلمات ممنوع (هر خط یک مورد)')}</span><textarea className="input" rows={4} value={m.blockedWords.join('\n')} onChange={e=>moderate({blockedWords:e.target.value.split('\n')})} onBlur={()=>moderate({blockedWords:m.blockedWords.map(v=>v.trim()).filter(Boolean)})}/></label>
   {check(t('Block invitation links','مسدودکردن لینک دعوت'),m.blockInvites,v=>moderate({blockInvites:v}))}{check(t('Block unapproved links','مسدودکردن لینک‌های تأییدنشده'),m.blockLinks,v=>moderate({blockLinks:v}))}
   <label className="field"><span>{t('Allowed domains (one per line)','دامنه‌های مجاز (هر خط یک مورد)')}</span><textarea className="input" rows={2} value={m.allowedDomains.join('\n')} onChange={e=>moderate({allowedDomains:e.target.value.split('\n')})} onBlur={()=>moderate({allowedDomains:m.allowedDomains.map(v=>v.trim().toLowerCase()).filter(Boolean)})}/></label>
   <div className="bot-form-grid">{num(t('Maximum mentions','حداکثر منشن'),'maxMentions',0,100)}{num(t('Messages per window','پیام در بازه'),'maxMessages',2,100)}{num(t('Window seconds','طول بازه به ثانیه'),'windowSeconds',2,120)}{num(t('Repeated messages allowed','تکرار مجاز پیام'),'maxRepeats',1,50)}{num(t('Capital letters %','درصد حروف بزرگ'),'capsPercent',10,100)}{num(t('Minimum letters for caps rule','حداقل حروف برای قانون حروف بزرگ'),'minCapsLength',5,1000)}{num(t('Maximum attachments','حداکثر پیوست'),'maxAttachments',0,10)}{num(t('Timeout seconds','مدت تایم‌اوت به ثانیه'),'timeoutSeconds',60,2419200)}{num(t('Warnings before timeout','اخطار تا تایم‌اوت'),'warningThreshold',1,100)}</div>
   <label className="field"><span>{t('AutoMod action','عملیات مدیریت خودکار')}</span><select className="select" value={m.action} onChange={e=>moderate({action:e.target.value as Moderator['action']})}><option value="block">{t('Block message','مسدودکردن پیام')}</option><option value="timeout">{t('Block and timeout','مسدودکردن و تایم‌اوت')}</option></select></label>
   {multiRoles(t('Exempt roles','نقش‌های معاف'),m.exemptRoleIds,v=>moderate({exemptRoleIds:v}))}
   <fieldset className="bot-role-options"><legend>{t('Exempt channels','کانال‌های معاف')}</legend>{channels.map(c=><label key={c.id}><input type="checkbox" checked={m.exemptChannelIds.includes(c.id)} onChange={e=>moderate({exemptChannelIds:e.target.checked?[...m.exemptChannelIds,c.id]:m.exemptChannelIds.filter(id=>id!==c.id)})}/>{c.name}</label>)}</fieldset>
   <p className="faint">{t('Owners and members with moderation permissions are exempt. Chat commands: /bothelp','مالک و اعضای دارای مجوز مدیریت معاف‌اند. راهنمای فرمان‌ها: /bothelp')}</p>
  </>:null}
  {tab==='community'?<>
   {check(t('Log server events','ثبت رویدادهای سرور'),m.logsEnabled,v=>moderate({logsEnabled:v}))}
   {check(t('Temporary voice channels','کانال‌های صوتی موقت'),m.temporaryVoiceEnabled,v=>moderate({temporaryVoiceEnabled:v}))}
   <label className="field"><span>{t('Temporary voice category','دسته کانال صوتی موقت')}</span><select className="select" value={m.temporaryVoiceCategoryId||''} onChange={e=>moderate({temporaryVoiceCategoryId:e.target.value||null})}><option value="">{t('No category','بدون دسته')}</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
   {num(t('Delete after idle seconds','حذف پس از زمان بیکاری به ثانیه'),'temporaryVoiceIdleSeconds',60,3600)}
   {check(t('Temporary invites','دعوت‌نامه‌های موقت'),m.temporaryInvitesEnabled,v=>moderate({temporaryInvitesEnabled:v}))}
   <p className="faint">/tempvoice · /templink · /profile · /credits · /daily · /rep · /colors</p>
   {check(t('Protect against destructive administration','محافظت در برابر عملیات مدیریتی مخرب'),m.protectionEnabled,v=>moderate({protectionEnabled:v}))}
   <div className="bot-form-grid">{num(t('Maximum actions per window','حداکثر عملیات در بازه'),'maxActionsPerWindow',1,100)}{num(t('Protection window seconds','بازه حفاظت به ثانیه'),'protectionWindowSeconds',5,3600)}</div>
   {multiRoles(t('Protected roles','نقش‌های محافظت‌شده'),m.protectedRoleIds,v=>moderate({protectedRoleIds:v}))}
   <fieldset className="bot-role-options"><legend>{t('Protected members','اعضای محافظت‌شده')}</legend>{members.map(u=><label key={u.id}><input type="checkbox" checked={m.protectedUserIds.includes(u.id)} onChange={e=>moderate({protectedUserIds:e.target.checked?[...m.protectedUserIds,u.id]:m.protectedUserIds.filter(id=>id!==u.id)})}/>{u.displayName}</label>)}</fieldset>
   <fieldset className="bot-role-options"><legend>{t('Protection whitelist','افراد مستثنی از حفاظت')}</legend>{members.map(u=><label key={u.id}><input type="checkbox" checked={m.protectionWhitelistIds.includes(u.id)} onChange={e=>moderate({protectionWhitelistIds:e.target.checked?[...m.protectionWhitelistIds,u.id]:m.protectionWhitelistIds.filter(id=>id!==u.id)})}/>{u.displayName}</label>)}</fieldset>
   {check(t('Enable starboard','\u0641\u0639\u0627\u0644 \u06a9\u0631\u062f\u0646 \u0627\u0633\u062a\u0627\u0631\u0628\u0648\u0631\u062f'),m.starboardEnabled,v=>moderate({starboardEnabled:v}))}
   {channelSelect(t('Starboard channel','\u06a9\u0627\u0646\u0627\u0644 \u0627\u0633\u062a\u0627\u0631\u0628\u0648\u0631\u062f'),m.starboardChannelId,v=>moderate({starboardChannelId:v}))}
   {num(t('Star threshold','\u062d\u062f\u0627\u0642\u0644 \u0633\u062a\u0627\u0631\u0647'),'starboardThreshold',1,100)}

   {multiRoles(t('Roles members may choose themselves','نقش‌های قابل انتخاب توسط اعضا'),m.selfRoleIds,v=>moderate({selfRoleIds:v}))}
   <p className="faint">{t('Only cosmetic and ordinary chat roles are allowed. Administrative permissions are rejected.','فقط نقش‌های ظاهری و دسترسی عادی گفتگو مجازند؛ نقش‌های مدیریتی پذیرفته نمی‌شوند.')}</p>
   {check(t('Enable XP and levels','فعال‌کردن امتیاز و سطح'),m.levelingEnabled,v=>moderate({levelingEnabled:v}))}<div className="bot-form-grid">{num(t('Voice XP per minute','امتیاز ویس در دقیقه'),'voiceXpPerMinute',0,100)}{num(t('XP per message','امتیاز هر پیام'),'xpPerMessage',1,100)}{num(t('XP cooldown seconds','فاصلهٔ امتیاز به ثانیه'),'xpCooldownSeconds',10,86400)}</div>
   <h4>{t('Level rewards','پاداش سطح')}</h4>{m.levelRewards.map((r,i)=><div className="bot-form-grid" key={i}><select className="select" aria-label="XP type" value={r.type||'text'} onChange={e=>moderate({levelRewards:m.levelRewards.map((v,j)=>j===i?{...v,type:e.target.value as 'text'|'voice'}:v)})}><option value="text">Text XP</option><option value="voice">Voice XP</option></select><input className="input" aria-label="Reward level" type="number" min={1} max={1000} value={r.level} onChange={e=>moderate({levelRewards:m.levelRewards.map((v,j)=>j===i?{...v,level:Number(e.target.value)}:v)})}/><select className="select" aria-label="Reward role" value={r.roleId} onChange={e=>moderate({levelRewards:m.levelRewards.map((v,j)=>j===i?{...v,roleId:e.target.value}:v)})}><option value="">{t('Select role','انتخاب نقش')}</option>{roles.filter(v=>!v.isDefault).map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><button className="btn small" onClick={()=>moderate({levelRewards:m.levelRewards.filter((_,j)=>j!==i)})}>{t('Remove','حذف')}</button></div>)}<button className="btn" onClick={()=>moderate({levelRewards:[...m.levelRewards,{level:1,roleId:''}]})}>{t('Add reward','افزودن پاداش')}</button>
   <h4>{t('Automatic responses','پاسخ خودکار')}</h4>{m.responses.map((r,i)=><div className="bot-response" key={i}><input className="input" placeholder={t('Trigger phrase','عبارت محرک')} value={r.trigger} onChange={e=>moderate({responses:m.responses.map((v,j)=>j===i?{...v,trigger:e.target.value}:v)})}/><textarea className="input" rows={2} placeholder={t('Response; supports welcome variables','پاسخ؛ متغیرهای خوشامد پشتیبانی می‌شوند')} value={r.response} onChange={e=>moderate({responses:m.responses.map((v,j)=>j===i?{...v,response:e.target.value}:v)})}/>{check(t('Exact match','تطابق دقیق'),r.exact,v=>moderate({responses:m.responses.map((row,j)=>j===i?{...row,exact:v}:row)}))}<button className="btn small" onClick={()=>moderate({responses:m.responses.filter((_,j)=>j!==i)})}>{t('Remove','حذف')}</button></div>)}<button className="btn" onClick={()=>moderate({responses:[...m.responses,{trigger:'',response:'',exact:true}]})}>{t('Add response','افزودن پاسخ')}</button><p className="faint">/rank · /top</p>
  </>:null}
  {tab==='tickets'?<>{check(t('Enable private support tickets','فعال‌کردن تیکت خصوصی پشتیبانی'),m.ticketsEnabled,v=>moderate({ticketsEnabled:v}))}<label className="field"><span>{t('Ticket category','دستهٔ تیکت‌ها')}</span><select className="select" value={m.ticketCategoryId||''} onChange={e=>moderate({ticketCategoryId:e.target.value||null})}><option value="">{t('No category','بدون دسته')}</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{multiRoles(t('Support roles','نقش‌های پشتیبانی'),m.ticketSupportRoleIds,v=>moderate({ticketSupportRoleIds:v}))}<p className="faint">{t('Members can open a private ticket using the support button beside the message box.','اعضا می‌توانند از منوی GIF و استیکر تیکت باز کنند.')}</p></>:null}
  </fieldset>
  {tab==='embeds'?<div className="bot-embed-builder">
   {channelSelect(t('Destination channel','کانال مقصد'),channelId,v=>setChannelId(v||''))}
   <label className="field"><span>{t('Title','عنوان')}</span><input className="input" maxLength={256} value={embedTitle} onChange={e=>setEmbedTitle(e.target.value)}/></label>
   <label className="field"><span>{t('Description','توضیحات')}</span><textarea className="input" rows={5} maxLength={3000} value={embedDescription} onChange={e=>setEmbedDescription(e.target.value)}/></label>
   <label className="field"><span>{t('Accent color','رنگ')}</span><input type="color" value={embedColor} onChange={e=>setEmbedColor(e.target.value)}/></label>
   <label className="field"><span>{t('Footer','پاورقی')}</span><input className="input" maxLength={500} value={embedFooter} onChange={e=>setEmbedFooter(e.target.value)}/></label>
   {embedFields.map((field,index)=><div className="bot-form-grid" key={index}><input className="input" aria-label={t('Field name','عنوان فیلد')} maxLength={256} value={field.name} onChange={e=>setEmbedFields(rows=>rows.map((r,i)=>i===index?{...r,name:e.target.value}:r))}/><textarea className="input" aria-label={t('Field value','متن فیلد')} maxLength={1024} value={field.value} onChange={e=>setEmbedFields(rows=>rows.map((r,i)=>i===index?{...r,value:e.target.value}:r))}/><label><input type="checkbox" checked={field.inline} onChange={e=>setEmbedFields(rows=>rows.map((r,i)=>i===index?{...r,inline:e.target.checked}:r))}/>{t('Inline','کنار هم')}</label><button className="btn" onClick={()=>setEmbedFields(rows=>rows.filter((_,i)=>i!==index))}>{t('Remove','حذف')}</button></div>)}
   <button className="btn" disabled={embedFields.length>=25} onClick={()=>setEmbedFields(rows=>[...rows,{name:'',value:'',inline:false}])}>{t('Add field','افزودن فیلد')}</button>
   <section className="zdis-bot-embed" style={{borderInlineStartColor:embedColor}}><h4>{embedTitle}</h4><p>{embedDescription}</p>{embedFields.map((f,i)=><div key={i}><strong>{f.name}</strong><p>{f.value}</p></div>)}<small>{embedFooter}</small></section>
   <button className="btn primary" disabled={busy||!canManage||!channelId||(!embedTitle&&!embedDescription)} onClick={()=>void run(async()=>{await api.post(path+'/embeds',{channelId,embed:{title:embedTitle,description:embedDescription,color:embedColor,footer:embedFooter,fields:embedFields}});toast.success(t('Embed sent','پیام ارسال شد'));})}>{t('Send embed','ارسال پیام')}</button>
  </div>:null}
  {tab==='tickets'?<div className="bot-ticket-list">{tickets.map(ticket=><div className="bot-case" key={ticket.id}><span>{ticket.id.slice(0,8)} · {ticket.status}</span>{['claim','close','reopen'].map(a=><button key={a} className="btn small" onClick={()=>void run(async()=>{await api.patch(path+'/tickets/'+ticket.id,{action:a});await refreshTickets();})}>{a}</button>)}</div>)}</div>:null}
  {tab==='actions'?<>
   <p className="faint">{t('Every action checks your permission and the member’s role hierarchy.','هر عملیات مجوز شما و سلسله‌مراتب نقش عضو را بررسی می‌کند.')}</p>
   <div className="bot-form-grid"><label className="field"><span>{t('Action','عملیات')}</span><select className="select" value={action} onChange={e=>setAction(e.target.value)}>{['move','bulkRole','setColor','setXp','setLevel','resetXp','voiceKick','pointsSet','pointsIncrease','pointsDecrease','pointsReset','removeWarning','muteText','unmuteText','muteVoice','unmuteVoice','warn','clearWarnings','timeout','untimeout','kick','ban','unban','purge','lock','unlock','slowmode','nickname','role'].map(a=><option key={a}>{a}</option>)}</select></label><label className="field"><span>{t('Member / banned user ID','عضو / شناسهٔ کاربر بن‌شده')}</span><input className="input" list="bot-member-ids" value={userId} onChange={e=>setUserId(e.target.value)}/><datalist id="bot-member-ids">{members.map(u=><option key={u.id} value={u.id}>{u.displayName} (@{u.username})</option>)}</datalist></label>{channelSelect(t('Channel','کانال'),channelId,v=>setChannelId(v||''),action==='move'?['voice','stage']:undefined)}<label className="field"><span>{t('Duration seconds','مدت به ثانیه')}</span><input className="input" type="number" min={0} max={2419200} value={duration} onChange={e=>setDuration(Number(e.target.value))}/></label><label className="field"><span>{t('Messages to remove (1–100)','تعداد پیام برای حذف (۱ تا ۱۰۰)')}</span><input className="input" type="number" min={1} max={100} value={count} onChange={e=>setCount(Number(e.target.value))}/></label></div>
   <label className="field"><span>{t('Reason','دلیل')}</span><input className="input" maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label>{action==='nickname'?<input className="input" aria-label="Nickname" value={nickname} maxLength={32} onChange={e=>setNickname(e.target.value)}/>:null}{action==='ban'?check(t('Temporary ban','بن موقت'),temporary,setTemporary):null}{['role','bulkRole','setColor'].includes(action)?<><select className="select" aria-label="Assign role" value={roleId} onChange={e=>setRoleId(e.target.value)}><option value="">{t('Select role','انتخاب نقش')}</option>{roles.filter(r=>!r.isDefault).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select>{check(t('Remove role instead','حذف نقش'),removeRole,setRemoveRole)}</>:null}
   {(action.startsWith('points')||action==='setXp'||action==='setLevel')?<label className="field"><span>{t('Points','امتیاز')}</span><input className="input" type="number" min={0} max={1000000} value={points} onChange={e=>setPoints(Number(e.target.value))}/></label>:null}
   {action==='bulkRole'?<textarea className="input" aria-label="Member IDs" placeholder="Member IDs separated by commas" value={bulkUsers} onChange={e=>setBulkUsers(e.target.value)}/>:null}
   {action==='setColor'?<input type="color" aria-label="Role color" value={actionColor} onChange={e=>setActionColor(e.target.value)}/>:null}
   {action==='removeWarning'?<label className="field"><span>{t('Warning ID','شناسه اخطار')}</span><input className="input" value={warningId} onChange={e=>setWarningId(e.target.value)}/></label>:null}
   <button className="btn danger" disabled={busy} onClick={()=>{if(!window.confirm(t(`Apply ${action}?`,`عملیات ${action} اجرا شود؟`)))return;void run(async()=>{await api.post(path+'/actions',{action,points,xp:points,level:action==='setLevel'?points:undefined,color:actionColor,userIds:action==='bulkRole'?bulkUsers.split(/[\s,]+/).filter(Boolean):undefined,warningId:warningId||undefined,userId:userId||undefined,channelId:channelId||undefined,reason:reason||undefined,durationSeconds:duration,count,nickname,roleId:roleId||undefined,temporary,remove:removeRole});await refreshCases();toast.success(t('Action completed','عملیات انجام شد'));});}}>{t('Run action','اجرای عملیات')}</button>
   <h4>{t('Recent cases','پرونده‌های اخیر')}</h4>{cases.length?cases.map(c=><div className="bot-case" key={c.id}><strong>{c.action} · {c.username||'—'}</strong><span>{c.reason}</span><small>{c.id.slice(0,8)} · {new Date(Number(c.created_at)).toLocaleString()}</small></div>):<p className="faint">{t('No moderation cases yet.','هنوز پرونده‌ای ثبت نشده است.')}</p>}
  </>:null}
  {tab!=='actions'?<div className="bot-save"><span>{dirty?t('Unsaved changes','تغییرات ذخیره نشده'):t('Saved settings','تنظیمات ذخیره‌شده')}</span><button className="btn primary" disabled={busy||!canManage||!dirty} onClick={()=>void save()}>{busy?t('Working…','در حال اجرا…'):t('Save changes','ذخیرهٔ تغییرات')}</button></div>:null}
 </section>;
}
