import { useState } from 'react';
import { useI18n } from '../lib/i18n';
import { storageGet, storageSet } from '../lib/storage';
import type { GroupExpression } from '../types';
import { Icon } from './Icon';
const presets=[['hello','Hello','سلام'],['love','Love','عشق'],['party','Party','جشن'],['thanks','Thank you','ممنون'],['wow','Wow','شگفت‌انگیز'],['gg','Good game','بازی خوب'],['bye','Goodbye','خداحافظ'],['happy','Happy','خوشحال']];
export function MediaPicker({kind,expressions,onPick,onClose}:{kind:'gif'|'sticker';expressions:GroupExpression[];onPick:(token:string)=>void;onClose:()=>void}) {
 const {locale}=useI18n(),fa=locale==='fa';const [query,setQuery]=useState(''),[source,setSource]=useState('all'),[favorites,setFavorites]=useState<string[]>(()=>{try{const value=JSON.parse(storageGet('zdis.media-favorites')||'[]');return Array.isArray(value)?value.filter((id:unknown)=>typeof id==='string'):[];}catch{return [];}});
 const items=[...presets.map(([id,en,p])=>({id:'builtin_'+id,name:fa?p:en,search:en+' '+p,token:`<${kind}:${id}:builtin_${id}>`,url:`/media-presets/${kind==='gif'?'gifs':'stickers'}/${id}.${kind==='gif'?'gif':'png'}`,custom:false,server:''})),...expressions.filter(e=>e.type===kind).map(e=>({id:e.id,name:e.name,search:e.name,token:`<${kind}:${e.name}:${e.attachmentId}>`,url:e.url,custom:true,server:e.sourceGroupName||''}))];
 const visible=items.filter(i=>(!query||(i.search+' '+i.server).toLowerCase().includes(query.toLowerCase()))&&(source==='all'||(source==='custom'&&i.custom)||(source==='favorites'&&favorites.includes(i.id))||(source==='standard'&&!i.custom)));
 function toggle(id:string){const next=favorites.includes(id)?favorites.filter(v=>v!==id):[...favorites,id].slice(-100);setFavorites(next);storageSet('zdis.media-favorites',JSON.stringify(next));}
 return <div className="media-picker emoji-popover" role="dialog" aria-label={kind==='gif'?'GIF picker':'Sticker picker'}><header><strong>{kind==='gif'?'GIF':fa?'استیکرها':'Stickers'}</strong><button onClick={onClose} aria-label="Close media picker"><Icon name="close" size={18}/></button></header><input className="input" placeholder={fa?'جست‌وجو…':'Search…'} value={query} onChange={e=>setQuery(e.target.value)} autoFocus/><div className="media-picker-tabs">{[['all','All','همه'],['standard','Standard','عادی'],['custom','Server','اختصاصی'],['favorites','Favorites','علاقه‌مندی‌ها']].map(([id,en,p])=><button key={id} className={source===id?'active':''} onClick={()=>setSource(id)}>{fa?p:en}</button>)}</div><div className="media-picker-grid">{visible.map(item=><div className="media-picker-item" key={item.id}><button onClick={()=>{onPick(item.token);onClose();}} title={item.server?`${item.server} · ${item.name}`:item.name}><img src={item.url} alt={item.name} loading="lazy"/><span>{item.name}</span></button><button className="media-favorite" aria-label={`Favorite ${item.name}`} aria-pressed={favorites.includes(item.id)} onClick={()=>toggle(item.id)}>{favorites.includes(item.id)?'★':'☆'}</button></div>)}</div>{!visible.length?<p className="faint">{fa?'موردی پیدا نشد. موارد اختصاصی از تنظیمات سرور ← شکلک‌ها اضافه می‌شوند.':'No matches. Add custom media in Server settings → Expressions.'}</p>:null}</div>;
}
